spring.application.name=api-gateway

server.port=8080
# Eureka server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Fetch registry from Eureka (needed for calling other services)
eureka.client.fetch-registry=true

#jwt secret key
jwt.secretKey =gfegfewgewgvfuyerfyvrefveryrgverrgvvgyergyurvuyvvdsjvyfri


# Optional: show IP instead of hostname
eureka.instance.prefer-ip-address=true



