
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG


spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: posts-service
          uri: lb://POSTS-SERVICE
          predicates:
            - Path=/posts/**
          filters:
            - StripPrefix=1
            - name: AuthenticationFilter

        - id: connection-service
          uri: lb://CONNECTION-SERVICE
          predicates:
            - Path=/connections/**
          filters:
            - StripPrefix=1
#            - name: AuthenticationFilter