spring.application.name=connection-Service

server.port=9030

#server.servlet.context-path=/connections
spring.neo4j.uri= bolt://localhost:7687
spring.neo4j.authentication.username= neo4j
spring.neo4j.authentication.password=admin1234

#Expose Actuator endpoints
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always