spring.application.name=posts-service


server.port = 9010

my.property = posts-service-SIT

#server.servlet.context-path=/posts
spring.jackson.time-zone=Asia/Kolkata
spring.datasource.url=jdbc:postgresql://localhost:5432/postsdb?options=-c%20TimeZone=Asia/Kolkata
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Eureka server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Fetch registry from Eureka (needed for calling other services)
eureka.client.fetch-registry=true

# Optional: show IP instead of hostname
eureka.instance.prefer-ip-address=true

